### ISSUE TITLE
Can you download documents directly from source?

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#106]
The command I am using 99% of the time is

```
papis add --from-doi 'XXX/XXXX-XXXX' /tmp/document.pdf
```

The issue is that I need to download the document before hand, save it, and allow papis to copy it. Is there currently a way to employ a `wget` directly? For example:

```
papis add --from-doi --wget 'https://pubs.acs.org/doi/pdf/XXXXXXX-XXXX'
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/30 (Duplication warnings on different documents).

**Comment by alejandrogallo** [comment]
Doesn't it do it already?
For me it does it, what happens if you do this?
```
papis add --from-doi 10.1021/ed044p128
```
I mean of course you have to be doing it from the university
or whatever, or configure a proxy. But otherwise
usually crossref finds out a `doc_url`
and then papis adding tries that `doc_url` out.

**Comment by michaelplews** [comment]
So it does! I can't believe I didn't know already. Thanks, and keep up the great work!

**Comment by jessebett** [comment]
I'm interested in the `--wget` aspect of this issue, but your solution only discussed the `--from doi`.

I am trying out papis as an alternative to Mendeley, where my citation work flow would involve having the pdf url open in a browser, and then dragging it into mendeley where it would automatically populate the info fields. I am trying to do something similar here, but `--from-url` does not parse `.pdf` urls. 

The help text for `--from-url` says `Get document and information from agiven url, a parser must be implemented`. Is there no way to have even a naive parser that downloads the pdf the url is pointing directly to, and then look at pdf metadata to fill the info. Even if it's not successful I can correct the info. 

Right now I'm not doing anything more intelligent than downloading the file temporarily, adding it, finding it's bibtex, and using this to update. This is wildly inefficient. At least having a way to put the pdf directly into my library from the source url would cut out a few of those inefficient steps, even if that pdf metadata isn't feasible.

**Comment by michaelplews** [comment]
Hi @jessebett, 

I, too, am replacing Mendeley with papis. You've pointed out a fundamental difference in papis and Mendeley, which is that Mendeley will read PDF metadata while papis does not. Papis merely uses information it gathers from the web to fill in the metadata.

I do like the idea of being able to parse a pdf without requiring an internet connection though, although @alejandrogallo might have other ideas. 

@alejandrogallo what are your thoughts on this?

**Comment by jessebett** [comment]
@michaelplews without the internet connection is secondary to my question though. I just want to have a more streamlined pipeline to cite things from the pdf url. This is how most people will send me papers. Often the arxiv pdf url, which is fine. It's a bit of a hassle to go from that pdf url to the full arxiv page, so if arxiv pdf urls were parsed that would be great too. But also I often just get pdf links hosted somewhere else, like on authors personal pages. Mendeley and Zotero can handle just dragging those urls into them and parsing all that stuff. It would be nice if, at the very least, I could copy that pdf url and get even just the pdf downloaded (and attempted metadata filling).

You're right though, an added benefit of this might be to allow offline parsing, but that is definitely not my priority. 

Like, especially if it tried to get some metadata, successfully obtained maybe a DOI, and then used the `--from-doi` to get at the rest of the metadata.

**Comment by michaelplews** [comment]
@jessebett Ah I understand. I like the idea of getting the doi from the metadata and then running it. as `--from-doi`. This would also be a nice introduction to eventually having full metadata parsing. I'll start looking into options for this. Feel free to file a pull request if you figure it out before I do though! Thanks for the suggestion.

**Comment by jessebett** [comment]
Unfortunately I definitely don't have the bandwidth right now to figure this out for myself. I'm piggybacking this issue hoping it will resolve like my previous issue with @alejandrogallo dropping a nice bash script for me, having already thought of and solved my problem.

**Comment by michaelplews** [comment]
How about this?

```
function papis-pdf { papis add --from-doi="`pdftotext $1 - -f 1 -l 1 | grep --ignore-case doi: | awk '{ print $2 }'`"} 
```

and use it as `papis-pdf /tmp/paper.pdf`

Very hacky but it might get you where you're going

**Comment by avonmoll** [comment]
In the slightly longer term, one might consider using the python library [PDFx](https://github.com/metachris/pdfx). It looks like you can hand it a URL and get the metadata back all in a couple lines of python. I do wonder, though, how many PDFs have the DOI embedded in the metadata? I checked several from my library and it is missing. This is especially true if the PDF is a preprint (unless the original author specifies the metadata from the tex source).

**Comment by michaelplews** [comment]
If we're trying to replicate Mendeley behaviour, I'm sure there isn't a single answer. Mendeley probably has a variety of parsing that it applies until it finds a DOI or other identifier. If we want to implement this behaviour, it will likely require a variety of fallback options to maximize the success rate.

@avonmoll PDFx looks like a good way to implement metadata searching, thanks for the link!

**Comment by alejandrogallo** [comment]
Hello guys, sorry for the delay, I'm quite busy lately.

# Improving downloaders

@jessebett
About arxiv, you can just do this, there is an arxiv parser for it, i.e.


```
papis add --from-url https://arxiv.org/pdf/1810.03653
papis add --from-url https://arxiv.org/abs/1810.03653
papis add --from-url arxiv:1810.03653
```

all of them work in principle.

Maybe we should document better all parsers already existing in

```
papis/downloaders
```

Maybe we should also write some documentation about how to write new
downloaders, for people that need from a specific journal, I from time to time
implement a couple, but of course I know exactly what they do.

Parsing metadata from pdfs
==========================

I implemented this once using `pdfminer2`, however it was annoying
and at the end of the day as @avonmoll said not so many documents
had meaningful metadata attached. I am of course open, however
my experience with it is sadly discouraging.

I also did some experiments with `pdfx` to get dois from all my library,
and what I found out is not appealing, only around 10 pdfs from around
500 had a real `doi` metadata entry. Converting into text is also an option,
and there are some projects doing it, but I think it's also too much of a
hustle to implement ourselves, specially since providers like `crossref`
provide such an amazing service by the sole input of the `doi`.

In my opinion we should strive to fully utilize the resources of

- https://dblp.uni-trier.de/
- https://crossref.org
- https://dissem.in
- https://pypi.org/project/isbnlib/
- https://arxiv.org

from which only

- https://dblp.uni-trier.de/

is at the moment not explored at all in papis.

# Comparison with Mendeley

I have never used Mendeley, however I have heard abouth this magical
way of getting information, I don't know exactly how they do it.
I mean, I would say papis could do something similar if it was just possible
to get the `title` and the `author` of the pdf, like when you do

```
papis update --auto mypaper
```

Whenever you do this command right now papis tries to get information from
the above mentioned sources.
For my personal purposes all this is enough, however of course we can always
improve the workflow


I think I touched all the points, feel free to disagree!

**Comment by jessebett** [comment]
Hi @alejandrogallo 

Thanks for your reply. I'm quite enjoying papis so far.

Hm, I don't know what I was doing wrong but when I initially posted this issue I thought the behaviour I was hoping for wasn't working. Trying now though it appears to be supported, so I was probably just doing something dumb. Specifically I thought that `papis add --from-url https://arxiv.org/pdf/1810.03653.pdf` was throwing a `Exception: I can't understand the expected extension pdf` error, but I just did that and it's working so... great!

Aside from the (likely complicated) magic associated with getting useful metadata from a pdf, the matter of just getting the pdf into the library from a `*.pdf` url involves downloading the file. Since it is obviously not feasible to have a parser for every possible host of pdfs, I think it would be nice if the default behaviour when provided such a url should be to download the pdf, and maybe try to apply these potential future magic metadata collection.

For instance, right now I would like to add a pdf hosted directly on a researcher's website (which obviously you can't write a useful parser for).

`papis add --from-url https://www.cs.toronto.edu/~rsalakhu/papers/dbn_ais.pdf` however returns the `Exception: I can't understand the expected extension pdf`. Ideally this command would fall back on a naive 'parser' which would be to just download the pdf into the papis library, (maybe one day do future metamagic), but otherwise let me edit/update its papis info manually since it was not parsed. 

In the OP I originally took this to be the intention of something like `papis add --wget ...` instead of hijacking `--from-url` but I don't see why these should be separate options. I think this is a reasonable fallback to providing url's directly to pdfs from not-explicitly-parsed sites.

Regarding metadata, maybe Mendeley was a lofty example. However, Zotero has this functionality too. For instance, if I open up the Zotero osx app, and drag that pdf from above (directly from the author's website) into my library it will populate the fields. Maybe it's possible to see how Zotero achieves this?
