### ISSUE TITLE
Picker: Scroll to show last entry

### ISSUE THREAD

**Issue by michaelcadilhac** [papis/papis#130]
When the picker displays more entry than can fit in the screen, and the user scrolls to the last entry, it is not displayed entirely. There is however no way to see it entirely, AFAICS—with other entries, one can go to the next entry to reveal the missing bits of the previous one.  Compare:

![scjzjegz](https://user-images.githubusercontent.com/5656935/49655281-258b6000-fa32-11e8-894b-f5fe012d7815.png)

and

![scrliyun](https://user-images.githubusercontent.com/5656935/49655280-24f2c980-fa32-11e8-9a26-68e0b09607db.png)

Cheers;
M.

PS: Beautiful piece of software, big fan.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @alejandrogallo, @nico202, and @michaelplews.

Possibly related issues are https://github.com/papis/papis/issues/122 (Picker for tags), and https://github.com/papis/papis/issues/88 (New picker, dump curses dependency).

**Comment by alejandrogallo** [comment]
Helo @michaelcadilhac , I understand what you mean, and you're indeed right.
I'd like to improve the picker and make it a little bit more robust, but time...

So a way of going around it for now is scrolling, which probably you were not aware of, so you can
press `ctrl+e` and `ctrl+y` to scroll just as in vim. Then you'll be able to see the last entry, i.e.

![07-12-18_18 17 17](https://user-images.githubusercontent.com/12715358/49662687-d4d53080-fa4c-11e8-9479-75fd2b651bdd.jpg)

and after scrolling

![07-12-18_18 17 21](https://user-images.githubusercontent.com/12715358/49662703-dbfc3e80-fa4c-11e8-8d90-e0829032b970.jpg)

However I'll leave the issue open in order to implement in the future the showing of the last entry
automatically.
Thanks for reporting!

**Comment by alejandrogallo** [comment]
This is fixed in the new papis pick
    https://asciinema.org/a/9Wz9JZhl0kl87JRx53hvsRSsH
