### ISSUE TITLE
Process multiple entries: papis add --from-bibtex

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#132]
It would be nice to be able to process multiple entries when adding from a .bib file. I tried to do this and papis stated that it would only process the first entry. Is there any reason to ignore entries after the first? I think I could make a PR, but am pretty busy right now :(

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/38 (Multiple authors in bibtex), https://github.com/alejandrogallo/papis/issues/37 (papis add fails with FileNotFoundError), https://github.com/papis/papis/issues/73 (Add bibtex-journal-key option), https://github.com/papis/papis/issues/100 (papis add has permission issues), and https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn).

**Comment by alejandrogallo** [comment]
Hi @avonmoll , sorry for the dealy answering.
You mean it should prompt you for the one that you want as in a picker?

**Comment by avonmoll** [comment]
Suppose I have the following file, let's say `new_papers.bib`. 
```bibtex
@article{Doe2012a,
    author  = {J. Doe},
    title   = {Lorem Ipsum -- Part I},
    journal = {J. Dolor Sit Am.},
    volume  = {1},
    pages   = {1--10},
    month   = {1},
    year    = {2012},
}

@article{Doe2012b,
    author  = {J. Doe},
    title   = {Lorem Ipsum -- Part II},
    journal = {J. Dolor Sit Am.},
    volume  = {2},
    pages   = {11--20},
    month   = {2},
    year    = {2012},
}
```

I would like to add both of these papers to my papis library with a single command:

`papis add --from-bibtex new_papers.bib`

And then papis would process the first article, `Doe2012a` and do any sort of interaction and/or confirmation as dictated by user's settings, e.g., and then process `Doe2012b` afterwards in similar fashion. As I mentioned in the OP, when I tried doing this, I get a message from papis explicitly saying it will only process the first entry.

**Comment by alejandrogallo** [comment]
Hi @avonmoll,
I understand completely your point but I don't think it is advisable since it would confuse
many users, however before we discuss further the matter let me offer you an alternative.

I've been writing for some time now a scrip `papis-bibtex` to interact with the bibtex of my papers
or theses or any bibtex file. It is still very fresh and I just had it in my dotfiles but I uploaded to
the `papis/scripts` repository and I think it's quite readable and hackable right now.
Maybe you can take a look.

https://github.com/papis/scripts/tree/master/papis-bibtex

What you're suggesting could be done with this script in the following way for instsance
(if you had the dois...)
```
papis bibtex                            \
  read new_papers.bib                   \ # Read bib file
  cmd 'papis add --from-doi {doc[doi]}'   # For every entry run the command
```
I use it for opening some papers for instance
```
papis bibtex read new_papers.bib open
```
or to add papers to the bib
```
papis bibtex          \
  read new_papers.bib \ # Read bib file
  add einstein        \ # Pick a document with query 'einstein' from library
  add heisenberg      \ # Pick a document with query 'heisenberg' from library
  save new_papers.bib   # Save in new_papers.bib
```

or if I update some information in my papis `yaml` files then I can do
```
papis bibtex          \
  read new_papers.bib \ # Read bib file
  update -f           \ # Update what has been read from papis library
  save new_papers.bib   # save everything to new_papers.bib, overwriting
```

Maybe this is also interesting for you guys:
@michaelplews @michaelcadilhac @JP-Ellis @klgunst

**Comment by avonmoll** [comment]
I've not tested it out yet, but that should suit my purposes just fine!

**Comment by alejandrogallo** [comment]
FYI: I updated it a bit and add some docu
https://github.com/papis/scripts/tree/master/papis-bibtex
