### ISSUE TITLE
Jinja formatting breaks matching (+ doc fix needed?)

### ISSUE THREAD

**Issue by gaalcaras** [papis/papis#170]
Hi there,

I've been trying out papis for a few weeks. I really like it overall, and I'm excited to leave Zotero behind and switch to papis permanently. However I've found a few areas where papis could definitely benefit from some polish.

For instance, I've been using the jinja2 formatting for `header-format`:
```
format-jinja2-enable = True
header-format = <ansired>{{doc.html_escape['title']}}</ansired>
  {%% if doc.has('journal') %%} in <violet><italic>{{doc.html_escape['journal']}}</italic></violet>{%% endif %%}
  <ansigreen>{{doc.html_escape['author']}}</ansigreen>
  <blue>({{doc.html_escape['year']}})</blue> {%% if doc.has('tags') %%}[<ansiyellow>{{doc.html_escape['tags']}}</ansiyellow>]{%% endif %%}
  <br/>
```

First, note that I had to use two `{%% ... %%}` instead of `{%- ... -%}` as written [in the documentation](https://papis.readthedocs.io/en/latest/configuration.html). I don't know if that's just me (I run jinja 2.10.1). If you can reproduce it, I can fix the documentation.

The real problem here is that jinja2 formatting breaks matching. When I run `papis open` for example, I can't find anything when I type "Bayesian". I then realized that the matching only runs on the name of the fields ("title", "tags", "year", etc.) but not their actual value! So typing any substring that's not included in the fields doesn't return anything, and of course otherwise it matches all the entries.

I would offer to look at the code if I wasn't so late on my own projects, hope you can reproduce the bug on your end and fix it. When I have more time though, I'd love to contribute to papis. I have a lot of ideas to improve on it (a hook system would be awesome).

BTW, I run papis v0.8.2.

**Comment by alejandrogallo** [comment]
Hello @gaalcaras 

I appreciate a lot your comments, thank you very much for taking the time to write so concisely.
I was just discussing jinja2 support with @teto the other day.
We are preparing version 0.9 which among other things, will polish the plugin architecture of papis
thanks to excellent Matthieu's suggestions. 

One of these things is the jinja2 support, which we thing should go out of papis and
reenter as a plugin for formatting.

This means that we have to thing how to implement a coherent formatting API so that these things
do not happen.

Again I know a workaround for your problem I think, it's the `match-format` configuration option,
which needs to be too a valid jinja2 format.

However I discourage you to invest time in jinja2 right now, since most probably will be soon pluginized as most of the other parts of papis right now, so that in the future you can install
`pip3 install papis-jinja2` and get the formatter through jinja2.

Thanks for your time!
Ale

**Comment by gaalcaras** [comment]
> We are preparing version 0.9 which among other things, will polish the plugin architecture of papis
> thanks to excellent Matthieu's suggestions.

Yes, I've seen that, exciting!


> One of these things is the jinja2 support, which we thing should go out of papis and
> reenter as a plugin for formatting.

That seems like the right choice.

> Again I know a workaround for your problem I think, it's the `match-format` configuration option,
> which needs to be too a valid jinja2 format.

Yep, that works!

> However I discourage you to invest time in jinja2 right now, since most probably will be soon pluginized as most of the other parts of papis right now, so that in the future you can install
> `pip3 install papis-jinja2` and get the formatter through jinja2.

Okay, thanks for your feedback. I've turned jinja off for now, the formatting is just a nice bonus :)
