### ISSUE TITLE
Make automatic git messages more specific

### ISSUE THREAD

**Issue by gaalcaras** [papis/papis#172]
One cool feature of papis is the integration with git, it reminds me a lot of how [pass](https://www.passwordstore.org) works. I only wish that more papis commands would integrate with it (something like `edit --commit` for example, or `addto --commit`).

One remark I would like to make is that the default commit messages ("Add document", "Add pdf") are really not specific enough for me. I think using such generic commit messages prevents from using the full potential of git. For example, the git log isn't really useful when all the commit messages are the same.

So I think papis should be more specific in its commit messages. I think it should at least reference the entry it modifies, something like: "Add document gelman2007" would be a good start. Even better would be to expose an option in the config file, like `git-format` that you could then set to a value of your own choice (using the `{doc[author]}, {doc[year]}, {doc[title]}` syntax).

**Comment by alejandrogallo** [comment]
hello @gaalcaras 
Thanks a lot for your feedback.
We were thinking about really making papis play well with git by using the python git interface.
I might just do this soon.

https://gitpython.readthedocs.io/en/stable/tutorial.html

Right now the git integration in add and addto was more of a hack so that I get my papers
added quickly, and these commits are from long ago, so I'd be interested in reviewing them for version v0.9.x...

I'm quite busy now trying to finish up version 0.9 though.

**Comment by gaalcaras** [comment]
> We were thinking about really making papis play well with git by using the python git interface.

Cool! I think the git integration is definitely one of the big plus of papis. Just for future reference, from glancing at the list of commands, I think git could integrate with `add`, `addto`, `edit`, `mv`, `rename`, `rm`, and `update`.

> I'm quite busy now trying to finish up version 0.9 though.

Of course, I'm sure you have enough on your plate as it is :)

**Comment by alejandrogallo** [comment]
I have implemented today a `--git` flag for the most relevant commands, however not yet for `mv`, and `rename`, maybe you want to take a look at it.

**Comment by alejandrogallo** [comment]
This is actually already covered now
