### ISSUE TITLE
General purpose interface

### ISSUE THREAD

**Issue by supersambo** [papis/papis#174]
I'm wondering if there is (or if there are plans for) a sort of general purpose interface to papis. I mean instead running running papis with a specific function and query such `papis edit Einstein` just opening all documents in the library and then deciding what to do (open, edit, export...).

**Comment by alejandrogallo** [comment]
Like a repl? shell kind of ?
I thougth about doing it with `prompt-toolkit`, yeah, but then there are many other
things on my list first.
But in principle such a system would be interesting, however me personally I don't
plan to do it, I would however give feedback if a person wants to do it.

**Comment by teto** [comment]
@supersambo this is sthg I have trouble with, like in mendeley you select a document then act upon it. With papis you prepare a command and select papers afterwards.
But then the papis API is pretty clean, almost everything is extensible so I hope to see some projects using papis as a backend. As a consequence, focusing on the backend should be more important IMO ?!

**Comment by supersambo** [comment]
@alejandrogallo  I was thinking of something comparable to mutt or ranger, if possible with vim keybindings.
@teto but I understand that the backend is more important now. Thanks for the quick answers anyway!

**Comment by teto** [comment]
@supersambo ranger accepts python scripts I think so might be possible to hack around it xD @xenius wrote a GUI that I would love to see adopt papis https://github.com/papis/papis/issues/157#issuecomment-478479562

**Comment by alejandrogallo** [comment]
Once I tried to hack into ranger to do a papis tui, but I dessisted eventually.
The papis `tui` is a first step towards it, but it's a lot of work.
https://github.com/papis/papis/tree/master/papis/tui

This tui is in need of extensions, one could read through it and declare bindings
https://github.com/papis/papis/blob/1bbcfc001dd4449f9f99e89b4a63bd04f0373d4f/papis/tui/app.py#L87

or commands
https://github.com/papis/papis/blob/1bbcfc001dd4449f9f99e89b4a63bd04f0373d4f/papis/tui/app.py#L243

However we should write documentation etc. 

Right now it is kind of vim like, if you do `:open ` you will open the document etc...
But it's not documented and I haven't documented it because it's an experiment.

**Comment by teto** [comment]
The papis API is clean, it should be easy to create your own UI just importing papis.
Actually I would like to do one based around fzf.
You could also fork @Xunius 's https://github.com/Xunius/MeiTingTrunk to use papis as backend.

**Comment by supersambo** [comment]
Some time ago a started tinkering around with the built-in picker. I did make a bit of progress with some of the ideas I had. However, I quickly realized that the tui can get pretty laggy when a complete library with many documents is loaded. At least on my machine it gets worst when other heavy programs are running. Of course, this is no problem for the intended use as a picker for a few items.

I'm not sure if this has to do with prompt_toolkit or if there is a way to write this more efficiently. In any case it makes me wonder whether expanding on this is the best way to build a general purpose tui or if it would make more sense to start from scratch as it has been suggested here. 

I sum, my questions are:
Is prompt_toolkit slow?
Would it make more sense to use another library such as curses, urwid... and start from scratch?

By the way, here are some of the things I tried to implement so far:

[First attempts](https://imgur.com/a/A6SZgxI)

- a more modal logic. "Normal mode" is when the options list is focused so you can map j and k to go up and down. 
- allowing for multi-key-stroke key mappings. E.g. "gg" to jump to first entry
- status bar has a left and right side and can is provided with more infos
- info window can display user defined infos for individual entries and you can switch between them 
- a doc-match mode to search for queries like "author: <authorname>"

**Comment by alejandrogallo** [comment]
Thank you very much for your lines.
This looks great.
If speed is your concern, which I haven't really heard before for libraries of 3k documents,
then there are several things that can be done:

- one could tun off the coloring in prompt_toolkit
- maybe the multithreading is causing more problems than solutions in your system

I could also suggest maybe the `fzf` interface is more fitting to your needs, and maybe you could also improve it there.

Your changes are quite interesting, I would be a little bit
weary of implementing a modal logic, that would be nice but the default should be no modal logic since otherwise first of all we have to document it and further some users might not be used to it since they're no vim or related users.

However in general I have to say that prompt_toolkit has been more of a headache for me than a solution, it has always felt hacky and the interface changed quite a lot and I'm always afraid of updating it. I thing it is not soo difficult to implement again a pure curses, or a vim interface, so that you can fitler in vim (at some point papis had this too, but again, you can't force an editor onto your users). If you want to discuss it maybe we can do it in the github discussions rather thatn in this closed issue
