### ISSUE TITLE
consider merging projects?

### ISSUE THREAD

**Issue by kirk86** [papis/papis#178]
Hi and thanks for the library,
I was wondering if you guys would consider merging projects. ATM there are a couple others which petty much do same stuff but also bring some new features like some of those listed in the roadmap?

**Comment by alejandrogallo** [comment]
Thank you for your interest .
 I’m afraid I don’t really know what do you exactly mean.  Could you be more specific and say which projects you would consider for a merge ?

**Comment by kirk86** [comment]
Sure,
at the moment I think that in the roadmap it was mentioned among others, 1) indexing and 2) extracting metadata from pdfs to search services such as scholar,scopus,wos,crossref,...,etc.

Now in the same category of managing references I came across some other libs such as bibsearch and papers.

For instance bibsearch is a project which does indexing using a sqlite3-fts5, plus it allows to download complete proceedings directly from the different venues.

While papers had a way of extracting metadata from pdfs and in order to do full-text search against the different services.

**Comment by m040601** [comment]
+1 vote for this
was just checking bibsearch right now.

All these (niche) cli doc/bib/ref management tools like papis, pubs etc , really deserve that their developers cooperate (or at least know that the others exist and what the others are doing).

There is ALWAYS something missing in one, that the other might have already figured out.

**Comment by alejandrogallo** [comment]
I agree in general, but in particular it's quite difficult to do this. I already talked to the authors of pubs in order to join forces, and we reached the agreement that in the future we might join forces to maintain the bibtex python package.

One point of your explanation would also be to do a better job in `marketing`, this means, explaining more concisely what papis does and what it is not, and what it does differently, I agree on everything.  It's also a lot of time to do this concisely but let's give it a #todo then.
