### ISSUE TITLE
Export interactive query for scripts and piping back to papis

### ISSUE THREAD

**Issue by jessebett** [papis/papis#232]
Hi @alejandrogallo, 

First thanks for updating the `list` command to export notes in #225.

I am hoping for some help with scripting some common papis workflows. I suspect it is possible, and likely my problem boils down to just being inexperienced at more-than-trivial shell-scripts.

Primarily my issue is that I want to use the interactive screen to select an item, and then export it to a restricted query that applies only to the selected item so I can safely pipe that back to various other papis commands.

For example, I frequently want to search through papis for a file, open the document, and edit the notes. 

Right now this requires:
```
papis open query # takes me to visual selector to narrow down query
papis edit -n query # takes me back to visual selector to *again* narrow down query
```

What I'd like to do is be able to write a bash function that
```
doc_i_want = papis export --to-papis-id query # opens visual selector to narrow down query
papis open doc_i_want # opens only the document I've specified in the visual selector
papis -n doc_i_want # also edits its notes file
```

I'm having trouble with two aspects of the above, again apologies if this is largely due to inexperience writing shell scripts. 
1. trying to access the visual selector when setting variables internal to a function, or piping them, I get `warning: Output is not to a terminal (fd=1)`. 
2. is there a papis command that I can give a query, open the visual inspector, and have it output information that would uniquely identify the selection (such that it is the only result from this query). I called this `export --to-papis-id` above, I don't know what this should be.

Thanks for any suggestions you have here.

**Comment by alejandrogallo** [comment]
Helllo @jessbet
this is unfortunately something that is not possible within the context of `prompt_toolkit`
and I certainly would also find useful to be able to do
```
folder=`papis list query`
papis open --doc-folder $folder
papis edit --doc-folder $folder
```

The problem is that apparently `prompt_toolkit` has added this behaviour only recently.
The problem is that the author of `prompt_toolkit` did not want to support this, but recently he inmplemented something tackling this issue
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/502

Currently is not possible to do this consistently.
However there is a hack, if you replace in the `papis/pick.py` file the stdout by the stderr, it works.

Basically the change that `prompt_toolkit` did ( which they did not release yet to the best of my knowledge), is doing the following example code

```python

from prompt_toolkit import prompt

import sys

if __name__ == '__main__':

    oldstdout = sys.stdout

    # without this a bash line of
    # a=$(python3 test.py)
    # would not work, like this it works.
    if not sys.stdout.isatty():
        sys.__stdout__ = sys.stderr
        sys.stdout = sys.stderr

    answer = prompt('Give me some input: ')

    sys.__stdout__ = oldstdout
    sys.stdout = oldstdout

    print('You said: %s' % answer)


```

I pushed a version of the `papis/pick.py` that basically does this and it works.
However I don't know how much of this is an ugly hack, however since the
`prompt_toolkit` developers have not yet pushed the relevant code, I'm inclined to
merge this for `v0.9.1`.

**Comment by alejandrogallo** [comment]
This is duplicated with #235, discussion should continue there.
