### ISSUE TITLE
Full-text search implementation

### ISSUE THREAD

**Issue by nico202** [papis/papis#27]
I'm looking at the roadmap.
The first point ("PDF or general document type content indexing") is what I'm referring here to "full-text search".
One way would be to just extract text and use something like xapian (used by notmuch for mail indexing) that is a wonderful library. However, the already existing [recoll](http://www.lesbonscomptes.com/recoll/) search tool already uses it. It is capable of converting a variety of [file formats]( http://www.lesbonscomptes.com/recoll/features.html#doctypes) including pdf files (by using poppler pdftotext).

IMHO taking advantage of their [python API](https://www.lesbonscomptes.com/recoll/usermanual/webhelp/docs/RCL.PROGRAM.PYTHONAPI.INTRO.html) could do everything we need.

I wanted to hear here opinions
Nicolò

**Comment by kskyten** [comment]
I have been looking to do something similar. At the moment Recoll does not fully support portable indexes (see [this issue](https://opensourceprojects.eu/p/recoll1/tickets/21/)). [DocFetcher](http://docfetcher.sourceforge.net/en/index.html) is also one option (see this discussion datalad/datalad#1996).

**Comment by alejandrogallo** [comment]
Thank you for your great input. It seems that you guys are much more into
this than me so you'll have to bear with me.

So summarizing, what I understood about the projects is:

Recoll
------

  - Basically xapian with full text search and GUI (very vaguely stated).
    Which is good for us, maybe we can even take advantage of their GUI.
  - The main advantage is that they already have a python API and they have
    good documentation.
  - No fully portable indexing (yet), this means that if
    you have your papers in a removable media for instance the indexing
    file has to be stored in the computer and not in the removable media.
    However for many use cases this might no be a problem for many users,
    in my opinion. AND it might get fixed in the future according to
    the discussion.

DocFetcher
----------

  - very portable.
  - Java-based, fast and hopefully stable.
  - No apparent python API
  - Nothing against it, only that if they have no python API
    is going to be quite a lot of work to write a wrapper if none of us
    is experienced with the program.

Way to go?
-----------
The primitve caching system that is now implemented in papis
can be turned off on a library basis with the ``use_cache``
setting. I don't think it would be outlandisch to implement
for instance a recoll-based module and let the user decide if
she wants to use it. After all the user will have to install Recoll
or DocFetcher himself in general, so it makes sense to give them
the choice of using it or not using anything at all.

Question
--------
In my opinion both alternatives are quite good, however I have a question
for you guys, do you think the [query language](http://papis.readthedocs.io/en/latest/queries.html)
is adequate or should we use the respective query languages of the indexing
programs?

**Comment by kskyten** [comment]
Few things to add. Recoll is Linux only as fas as I know, whereas DocFetcher is cross-platform. On the other hand, the documentation of DocFetcher states: "Please note that due to lack of time we currently have no plans to extend DocFetcher in any significant way", while Recoll seems to be actively developed. The biggest gripe with DocFetcher for me is the inability to specify how to open the files. This, for example, prevents pdf files from being opened at the page of the search result.

A first step would be to just use Recoll or DocFetcher independently from papis. This doesn't require any additional work on our part, but should be pretty useful. What would be really cool is combining the metadata from papis and a full-text index. I think making this as an optional setting is a good idea.

Are you aware of [Whoosh](https://pypi.python.org/pypi/Whoosh)? It is a pure-Python full-text indexer. I recommend using it for querying the metadata. It seems to have a lot of nice features including a powerful query language. One possibility would be to use whoosh for indexing the content as well, but in that case we would have to implement text extractors for different file formats ourselves.

**Comment by FSA1** [comment]
DocFetcher 1.1.20+
Python scripting API for programmatically launching searches and accessing the search results. See the explanation at the top of the file search.py, which can be found in the DocFetcher program folder.

**Comment by alejandrogallo** [comment]
Yes, that is interesting but I don't know how interesting is papis for people that already are using DocFetcher, could you comment on that?

I was thinking about using this project, which is a python module that interfaces with command line tools
https://github.com/btimby/fulltext
Maybe someone has some thoughts about it

**Comment by FSA1** [comment]
I found this discussion by chance, while looking for a way to integrate Goldendict and DocFetcher, I decided to help by posting information about the API. Good luck!
PS: Actually I still need help. ;-)

**Comment by teto** [comment]
The https://github.com/btimby/fulltext looks interesting. Before getting something into the core, maybe adding some hooks would allow to experiment a bit (e.g., update the db for this specific document on add). It could help with https://github.com/papis/papis/issues/172 as well (aka the user could run a git hook when a file is added/removed).

**Comment by alejandrogallo** [comment]
Looks interesting indeed, I don't know exactly how the stevedore hooks work, maybe we could experiment with them.

**Comment by maxigas** [comment]
This issue is closed by full text functionality is not documented and not both `recoll` and `DocFetcher` is missing from the code. This would still be an interesting feature to support. In fact, it would make me consider adoping `papis` as my daily driver.

**Comment by alexfikl** [comment]
> This issue is closed by full text functionality is not documented and not both `recoll` and `DocFetcher` is missing from the code. This would still be an interesting feature to support. In fact, it would make me consider adoping `papis` as my daily driver.

@maxigas Thank you for your interest in papis! I'm afraid this wasn't actually implemented (not sure why it was closed, maybe just because it was stale).

This type of functionality could probably be added as an external plugin (at least to start). There's [papisqa](https://github.com/isaksamsten/papisqa) that uses an LLM to query documents, so I imagine that a `recoll` plugin could be made in a similar fashion.

**Comment by jghauser** [comment]
Yeah, this would really be great, and I've been wanting to implement something like it for a while. It's just that I currently don't have the time for it. I've recently come across [this write-up](https://artifex.com/blog/explore-text-searching-with-pymupdf) regarding searching using `pymupdf` which might be interesting (for pdfs at least).

**Comment by maxigas** [comment]
OK thank you both for clarifying the state of full text search in papis. My own take on it is that `xapers` (a similar but less active open source project) does this by delegating the indexing to Xapian, the same backend that `recoll` uses. That fits into my workflow really well because I am also using `notmuch` to manage emails, and it is based on the same architecture of indexing documents with Xapian. So, the query language and underlying technology to search my emails and my reference database is the same. I doubt this is the case for many (potential) users, but it shows that Xapian can be easily integrated into Python projects and used conveniently for document indexing and full text search.

**Comment by alexfikl** [comment]
> OK thank you both for clarifying the state of full text search in papis. My own take on it is that `xapers` (a similar but less active open source project) does this by delegating the indexing to Xapian, the same backend that `recoll` uses. That fits into my workflow really well because I am also using `notmuch` to manage emails, and it is based on the same architecture of indexing documents with Xapian. So, the query language and underlying technology to search my emails and my reference database is the same. I doubt this is the case for many (potential) users, but it shows that Xapian can be easily integrated into Python projects and used conveniently for document indexing and full text search.

I agree that using something like Xapian is definitely the way to go with this. Doing the indexing and/or searching ourselves is likely going to just end up very slow even for moderate libraries.

It doesn't sound very difficult, just needs someone with the time to implement it :grin:

**Comment by jghauser** [comment]
As a fellow `notmuch` user, I definitely like the xapian idea! :smile: Definitely up for helping out/testing if you're feeling like working on this!
