### ISSUE TITLE
Project specific libraries

### ISSUE THREAD

**Issue by kskyten** [papis/papis#29]
It wasn't entirely clear from the documentation how to add files to a specific library. Is this possible? I would like to have all the related to a project contained within the project (i.e have the library inside a repository for a paper I'm writing, for example). To do this it would be convenient to have a local configuration file so that papis commands ran inside a project only affect the project specific library.

**Comment by alejandrogallo** [comment]
Thanks for pointing it out, if you have any suggestions of how to improve the documentation after my answer you're welcome ;) I pushed now an example of the exact behaviour you're describing in the documentation for the ``add`` command.

So in principle you can define as many libraries as you want and all papis commands
have effect on a library through the ``-l`` argument:
```
papis -l new-paper export --all --bibtex --out main.bib
```
will export all documents in the ``new-paper`` library defined in your papis config file, which
I guess in your case should live in ``~/.config/papis`` if everything went well.
You can take a look at my own configuration [here](https://github.com/alejandrogallo/dotfiles/tree/master/link/papis) you'll see that I have two libraries
books and papers defined.  All papis config settings are also overridable on a library basis.

A good thing is that you don't even need to define the library in your config file, if your paper repo is in
``~Documents/new-paper/`` and you want your library in ``~/Documents/new-paper/library/``
then you can do
```
papis --lib ~/Documents/new-paper/library WHATEVER
```
so, ``-l`` or ``--lib`` accept library names or paths that are to be interpreted as unnamed libraries.

I mean we could also implement a sort of a local-local configuration file so that you have a
``~/Documents/new-paper/.papis/config``, however this is not super standard, is this what you were looking for?

**Comment by kskyten** [comment]
Thanks, this is exactly what I was looking for. I'm still figuring out what the best workflow would be. My use case is to be able to automatically generate the bib file as a part of the build process. To do this I need to separate the papers that are relevant to the current project.

One way is to have project specific libraries as discussed. The other would be to add some kind of an unique identifier (tag) to each paper that is relevant to a specific project and then add them to the global library. In both cases I think it would be convenient to have this project locality automatically inserted when papis commands are run inside the project folder. Local configuration files are probably the easiest way to get this behaviour.

**Comment by alejandrogallo** [comment]
My approach would be to define a key,val pair in your desired documents, for instance in your
yaml files of the relevant papers you would have something like
```yaml
author: blah
title: bluh
project: new-paper-with-my-friend-joe
```
and then you can have makefile targets like:
```make
update-bib-from-papis:
  papis export "project = new-paper-with-my-friend-joe" --bibtex --all --out main.bib

update-papis-from-bib:
  papis update -i --from-bibtex main.bib 
```
This is a way of doing it, it depends on your workflow of course

**Comment by kskyten** [comment]
Yes, this is what I meant. For additional convenience it would be nice to be able to fill in the `project` key automatically.

Currently, as far as I understand to do the above workflow I would add a paper to papis and then manually add the project identifier to the relevant paper with `papis add --edit`. It would be nice to be able to do
```bash
cd project-A
papis add ...
```
and have the generated `info.yaml` be
```yaml
author: blah
title: bluh
project: project-A
```

**Comment by alejandrogallo** [comment]
I never thought about this... it seems too specific for me to be implemented extra, however I think
I know a papis way of doing it somehow, what about this:
Implement a `--with` flag to the `add` command to predefine key-val pairs, e.g.:
```
papis add --with "author = blah title = 'bluh blih'  project = project-A"
```
togetherr with a papis setting `add-with` so that you can override always the `--with` flag,
so, since we now have local config files, you could put in your local config file
```ini
[settings]
add-with = 'project = project-A'
```
and this would have effectively the exact effect that you are looking for, without really adding
new functionality to the `add` command, and the `--with` flag I wanted to implement at some point
anyways. 
This is kind of the most non-disturbing way possible I see right now. What do you think?

**Comment by kskyten** [comment]
Perhaps a nicer way would be to add hooks similar to git. So a project folder would look like this
```
project
├── main.tex
└── .papis
    ├── config
    └── hooks
        ├── add
        ├── commit-msg
        ├── post-commit
        └── pre-commit
```
and if the hooks were defined they would run at the appropriate point. For example the `post-commit` hook would be ran after the `info.yml` file was created to make modifications. These hooks could also be useful for other purposes [like making sure to cite the actual publication instead of the arxiv preprint ](https://github.com/bibcure/arxivcheck).

**Comment by alejandrogallo** [comment]
I think it is a very good idea, however I'll need some time to take a look at it, it would be nice
to be able to write the hooks in any language like the scripts but is not so straight forward.
But I think it's worthwhile adding hook capabilities in general to papis, for sure, would you want to give it a go yourself?

**Comment by avonmoll** [comment]
Is it possible to have a many-to-many relationship between documents and libraries (or documents and project tags?). I find myself re-using some foundational sources across my different manuscripts; in light of the previous comments, I'm imagining the following workflow:

A document that I cite often which has the following `info.yaml`

```yaml
author: A. Author
title: Authoritative Source
project:
    - project-one
    - old-paper
    - new-paper
```

When I need to build `new-paper` and update its .bib file:

```
papis export "project = new-paper" --bibtex --all --out main.bib
```

On a slightly related note, it would be nice to be able to manage this many-to-many relationship in some fashion other than editing `info.yaml` files all the time.

**Comment by alejandrogallo** [comment]
Hi!
Before answering, I've got a question:

Do you have all the documents in one library ? Or scattered across different
libraries ?

**Comment by avonmoll** [comment]
I'm envisioning using a single master library

**Comment by alejandrogallo** [comment]
I mean, it should work like this, have you tried it ?
If you run the commands that you wrote, it should work. 

> On  a slightly related note, it would be nice to be able to manage this many-to-many relationship in some fashion other than editing info.yaml files all the time.

What do you mean exactly? There might be many ways of doing it, you mean for instance
adding a class of papers into another project by doing

```
papis add-to-project 'project = new-paper' --project super-breakthrough
```

This functionality is easily implemented in a small script, we can do it.

**Comment by avonmoll** [comment]
The example you made is great! As for my other cryptic suggestion, I think what I had in mind was a kind of TUI wherein you could browse your projects and add/remove items from them. It could have two "panes": a list of projects on the left and the contents of the selected project on the right (similar to how ranger looks and feels). Perhaps this is overkill though, and the example you put together is a more papis way of doing it. Forgive me if I'm getting off topic!

**Comment by alejandrogallo** [comment]
Hi @avonmoll, don't worry, these issues are open for any discussion. The `TUI` is a todo,
which at some point will get done, the new picker using `prompt-toolkit` was the first step toward it,
however it will take still some time... Feel free to hack into
`papis/pick.py`, though :wink:
