### ISSUE TITLE
Extra line break when using header-format-file

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#291]
* papis version (`$ papis --version` or commit number): 0.11.1

I tested an identical format string in `header-format` and then again in a file and specified the file in `header-format-file`. In the latter case the headers always have an additional blank line at the end. I checked to make sure there was no extra newlines at the end of the header file. I also tried saving the file with different line ending conventions (unix/dos/mac, etc.) and the blank line was always present in the picker.

This is an extremely minor aesthetic inconsistency which is easily worked-around by just using `header-format`.

**Comment by alejandrogallo** [comment]
Are you using the Jinja or default papis formater ? It can be that from the header format file we have to remove the last line break `\n` here

https://github.com/papis/papis/blob/be18c4a141da0929b4eac1459af1c04b9df7cdc6/papis/pick.py#L74

one could do something like

```python
header_format = re.sub(r"\n\s*$", "", header_format)
```

I guess this would fix the issue. Do you think you'd have time to test this?
Otherwise I can test it at some point.

Cheers

**Comment by avonmoll** [comment]
Until this came up I never knew this but `read()` _always_ includes a newline character at the EOF. I think the reason is to be consistent with `readlines()` which includes `\n` at the end of each line. Looks like adding a call to `rstrip` will remove the trailing `\n`. I'll test it and make a PR.
