### ISSUE TITLE
Crossref importer using wrong link element

### ISSUE THREAD

**Issue by hrdl-github** [papis/papis#379]
papis, version 0.11.1

At the moment the crossref importer selects the second element of the `link` list https://github.com/papis/papis/blob/5f6085242b9195e37898bcf7da6d035b02c217b0/papis/crossref.py#L116-L119 This works for the test case (https://api.crossref.org/works/10.1103/physrevb.89.140501), but not for other cases (e.g. https://api.crossref.org/works/10.1137/070699640, which offers only a single element).

I don't know how common this behaviour is.

**Comment by alexfikl** [comment]
We apologize for the delay on this! There's a tentative fix in #480, which also fixes one of the tests that just had one link like in your example.

If you have the opportunity to test that, it would be great! Otherwise we can revisit later, but hopefully it works :grin: 

Thank you for the report and sorry again for the delay!

**Comment by alexfikl** [comment]
> Thanks, I haven't had the chance to test this as I haven't been actively using crossref lately.

No worries! Feel free to open some new bug reports if you notice anything that's off.
