### ISSUE TITLE
doi resolution is buggy

### ISSUE THREAD

**Issue by nico202** [papis/papis#54]
Hi, papis is failing add the paper from this doi:
`10.1145/3139513.3139518`

doing it manually, both crossref and doi.org are working.
I almost implemented papis add --automatic [ISBN/DOI/PMID] but I'm having problems with both isbnplus and doi resolvers working just for some papers/books

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
It's true, we'll have to look into it, it is weird...

**Comment by nico202** [comment]
I think I'll look at how zotero is doing it (https://github.com/zotero/translators) and I'll port it to papis

**Comment by alejandrogallo** [comment]
you mean this translator?

https://github.com/zotero/translators/blob/master/DOI.js

**Comment by nico202** [comment]
Uh but I saw that you are requiring habanero without actually using it, I'm I right? Then the first step would be to replace your custom downloader with it

(yes I was talking about it, that then uses crossref and datacite)

**Comment by alejandrogallo** [comment]
Hi, 

actually the habanero thing is on the `RODAMAP`, I'd like to use well-written
libraries for API of other services, and habanero appeared to be very good.

So I tinkered with it in the function `crossref.get_data` and exposed it in the
`papis explore` command, actually it works well to get papers directly from crossref
through scihub, i.e.
```
papis explore --crossref 'some nice interesting paper' --cmd 'papis scihub {doc[doi]}'
```

If you're in the mood you can actually clean up the code and replace everything with the 
habanero alternative, because the actual code now is prior to me knowing about the existence
of habanero... ;)

**Comment by nico202** [comment]
Yes I'm doing it
