### ISSUE TITLE
parse stdin

### ISSUE THREAD

**Issue by nico202** [papis/papis#61]
It would be useful to have something like

`papis list | head -1 | papis export --bibtex`

working

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Yes, I have also needed it. We can create a `--path-file` flag so that
papis should consider all the paths in some file as the documents that should be considered.

Then we could also do
```
papis list  | head -1 | papis export --bibtex --paths-file - 
```

The reason of adding a new flag would be that a path is not really part of the matching format in general,
so doing
```
papis open /path/to/file
```
while it would be sometimes useful, it will mess-up the querying, since now we have to interpret also
the query inputs as possible paths.
