### ISSUE TITLE
Somewhat spammy "Updating existing section 'settings'." messages

### ISSUE THREAD

**Issue by jghauser** [papis/papis#610]
With almost all commands, I now (since the changes [here](https://github.com/papis/papis/commit/463175b849150a5ea1e56b390c2d12fdb3fd0522) I think) get a ` Updating existing section 'settings'.` message. For instance, it will show if I do `papis list some_author`. If I'm understand things correctly, this is simply because my config is applied? Or is there something else behind it? If it's really just an info message, I think it might be best to not show it by default as it clutters the output and might even be (mis)interpreted to indicate that something is amiss. What do you think?

**Comment by alexfikl** [comment]
You're right that that's spammy that I'll make a PR to silence it (since I'm to blame :().

For some explanation of what I was thinking of there: I assumed that `register_default_settings` is mainly called by plugins to add new settings for themselves (e.g. `commands.bibtex`) and it would be bad if they overwrote some default sections. If I understand correctly, you're using it in `config.py` to add your settings?

**Comment by jghauser** [comment]
Yes, I have some of my settings in a `config.py` -- that's definitely what's going on here! Thanks for the quick fix, I already see a PR :)

Yeah, I do get the thinking about wanting to warn users if some plugin is up to funny things. I guess if that becomes a problem at some point, we can think of something a little more involved that is able to check if the settings are user-supplied or not.
