### ISSUE TITLE
Rofi GUI doesn't honour 'editor' option in .config/papis/config

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#64]
Trying to edit the info.yaml from rofi defaults to xdg-open even if the `editor` option is set in `.config/papis/config`.

Example:
```bash
$ papis gui --rofi
# rofi opens
# Alt+e opens info.yaml in xdg-open

$ papis config editor 
nano
```

**Comment by michaelplews** [comment]
I figured it out. `editor` and `xeditor` are two different options. Not having `xeditor` set was my problem.

If this is in the docs and I missed it, feel free to close

**Comment by alejandrogallo** [comment]
Hi Michael,

I agree that it might be confusing to some people, but strictly speaking it was in the
docs

http://papis.readthedocs.io/en/latest/configuration.html#config-settings-xeditor

the problem was that simply honouring `editor` would be problematic since for many editors (vim, nano...) you actually need some sort of gui substrate (in the case of nano, one would need to
open a terminal application executing nano which would edit the mentioned yaml file).
In order to avoid this I decided to take the `xeditor` shortcut.

I hope it's clear also for future FAQs.
Thanks!
