### ISSUE TITLE
work with existing file structure

### ISSUE THREAD

**Issue by emacsomancer** [papis/papis#83]
Is there a way to have papis *not* make copies of added pdfs, but rather leave them where there are and just create the appropriate file-location entry in the the .yaml file?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/28 (Making the metadata more structured).

**Comment by alejandrogallo** [comment]
Hi, thank you very much for your interest!
In short, no, there is currently not a way to do this, and I think we
should not implement yet another flag for that, I think, we can discuss.

I have one alternative for you that would spare me the work to implement
it.
You could in principle just create a hard link to the file before adding a
PDF and let papis copy that hard link to the file. It would be better
because we would not have to mess with relative paths in the info file etc.
And for you it would be besser because every time you change the location
you just have to update the link.

What do you think? You could even write a small papis bash script that
handles all of this for you, is this clear to you how to do it? I can help
you, however you have the documentation for the scripts too.

Cheers!

**Comment by emacsomancer** [comment]
Thanks, @alejandrogallo for your suggestion. I had thought a bit about hard links as a workaround. That wouldn't be ideal for syncing between different machines though. Maybe soft links would be another option that would work between for sync'ed machines (assuming the machines have the same relevant file structure). I'll look at the papis scripts to see how this might be done.

**Comment by alejandrogallo** [comment]
No worries, take a look at it if you can find a workaround. If not we can
discuss about it, but implementing it in papis would include also
hardcoding links, which for the generality across different machines would
be problematic too.

**Comment by alejandrogallo** [comment]
Hi @Xunius , thanks so much for your work and interest.
Ok, I mean, I do not know anyone that would be interested in that but I can add it in v0.7, which should
be ready this week... I hope! ;)

I was thinking about implementing it just as a flag
```
papis add document.pdf --link
papis add document.pdf -l
```
would this be acceptable for you guys that have to use this option so often ?

**Comment by alejandrogallo** [comment]
See issue #194
