### ISSUE TITLE
`document.load()` does not delete fields

### ISSUE THREAD

**Issue by moberst** [papis/papis#895]
First of all, absolutely massive fan of `papis`, big thanks to all who have worked on it.

I came across an issue while editing documents in `papis`:  If you edit a `.yaml` file via `papis edit`, and *delete* a key from the file, it is not reflected in the database.

I can provide a minimal working example if helpful.  But I believe I found the core issue - it is this line in `document.load()`, which is called in `papis.command.edit.run()` to update the document after editing.

https://github.com/papis/papis/blob/129773dd8b35a734d19206a1640b394179c224cd/papis/document.py#L454

Because this calls `self.update(data)`, which I understand to essentially be `dict.update(data)`, it does not delete keys from the dictionary that were removed in the file.

**Comment by alexfikl** [comment]
Thank you for the kind words and the nicely researched issue! :heart: 

I can't say I can think of a scenario where updating instead of overwriting is the right thing to do on `Document.load`, so this definitely sounds like a bug. Would you be willing to make a little pull request with a fix? (just adding a `self.clear()` before should do it?)

**Comment by moberst** [comment]
Done!
