### ISSUE TITLE
explore arxiv --author 'John Smith' returns articles from all Johns and all Smiths

### ISSUE THREAD

**Issue by bluehood** [papis/papis#95]
...rather than articles from John Smith.
Admittedly, articles by John Smith are listed before the others.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Hi and thanks,

so if you search in the usual way

https://arxiv.org/search/?query=John+Smith&searchtype=author&source=header

you also don't find right away articles by `John Smith`, the first  article is situated in place `45`,
maybe `John Smith` is a bad example ? Check out for instance

```
papis explore arxiv -a 'Robert Denk' pick
```

it works well and then of course since arxiv has to give you up to 20 articles (by default)
then you will get some extra ones...

**Comment by bluehood** [comment]
Hi,
thank you for your reply. Agreed, `Robert Denk` is a better example :smile: [arxiv gives 17 results](https://arxiv.org/search/?query=Robert+Denk&searchtype=author&abstracts=show&order=-announced_date_first&size=50) out of a maximum of 50 per page. Note that it does not add extra non-Robert-Denk results to get to 50.

I would argue that's the behavior one would expect from `papis explore arxiv` as well: if I ask for `papis explore arxiv -a 'Robert Denk' pick`, there is zero chance I will be interested in an article by `Robert Lazarsfeld`, and since 20 is the _max_, anyway, it's fine if only 17 results are returned instead, don't you agree?

**Comment by alejandrogallo** [comment]
Hi!
I did the test of trying to not pass the `max` argument into the arxiv `get_data` function,
and if I look for `robert denk`, and it looks weird

https://asciinema.org/a/2AYvN6wkIvEczEyYfbLlW2L8g

I don't know, it does not seem to have sane defaults the api, also if I look for `Garnet Chan`,
who has zillions of papers on arxiv, I only get 10

https://asciinema.org/a/vIxrNTkONOL29YkTmG17H1P56

**Comment by bluehood** [comment]
what if you use arxiv's API as you are using it now, _but_ you only take the first `max` results it returns?

**Comment by bluehood** [comment]
ok, thanks for looking into this. I experimented a bit and took a look at the arxiv [API manual](https://arxiv.org/help/api/user-manual): search for `%22`, it says that to look for pairs of words or multiple words together you need to enclose them in double quotes (i.e. `%22`).

In fact, the following works well:
```
papis explore arxiv -a '"Robert Denk"' pick
```
(note the double quotes inside the single quotes).

I suggest, as a favor to users, that you enclose all arguments that users pass to `papis explore arxiv` in double quotes, so that `papis explore arxiv -a 'Robert Denk'` actually searches for `"Robert Denk"` and not for both `"Robert"` _and_ `"Denk"`

**Comment by alejandrogallo** [comment]
@bluehood , this is an amazing piece of information that you found!!
Thanks so much! It works like a charm.

However, I think it would be detrimental to include the quotes without the user knowing,
since then you might want to match `John Smith` as well as `John R. Smith`, as was the case,
or in the case of the famous `Garnet Chan`, you'd be missing papers authored as `Garnet Kin Lic Chan`, which are also his papers. So, maybe adding this important piece of information as
documentation would be a nice thing, right ? What do you think as a users that got rightfully annoyed by it, would it have helped?

**Comment by bluehood** [comment]
yes, if it was listed in `papis explore arxiv -h`, and maybe there was even an example that showed it, i would have not fallen into the trap :smile:

**Comment by alejandrogallo** [comment]
Done! Beware of further papis traps!!
Again, thanks so much for your help!
