### ISSUE TITLE
Possible bug that appends .txt extension to info.yaml file?

### ISSUE THREAD

**Issue by Xunius** [papis/papis#98]
Hi,
I guess I'm really good at finding issues.
If I add a new document with `--no-document` flag, e.g.

```
papis add --no-document --from-bibtex lib.bib
```
or
```
papis add --no-document --set title 'some title' --set author 'Jesus'
```
papis will add the document. Then I use `papis open`, navigate to that `no-document` file and Enter, it gives this:

```
xdg-open: file '/path/to/library/to/folder/info.yaml.txt' does not exist
```
I guess the intended behavior is to open the `info.yaml` file if a document has no file attached to it, but a `.txt` extension is appended, so it finds nothing.

If so, I guess a fix is to change these part in `add.py`'s `get_file_name()`:

```
    if filename_basename=='info.yaml':
        filename = filename_basename
    else:
        ext=papis.utils.guess_file_extension(original_filepath)
        filename = "{}.{}".format(
            filename_basename, ext)
    return filename
```

BTW, why using a `guess_file_extension()` function, instead of calling `os.path.splitext(basename)[1]`?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
HI @Xunius ,

thanks for this, I just fixed this and also cleaned a little bit the add command, which
is kind of a mess, it's in the branch v0.8, I also removed the `--no-document` flag,
which I don't think it makes a lot of sense now to have it there, it's ok to have papis documents
without files, but it's going to be done by the end of the week, because I want to get some other
things done

By the way, I added some code to the `papis-zotero` project in
https://github.com/papis/papis-zotero

Where I intend to put the importer, it's already in place, one only hast to play with it a little bit more
and it'll be done, maybe you're also interested to take a look there.

**Comment by alejandrogallo** [comment]
The importer is now working in `papis-zotero`, do you know how to install from master the packages ?
Or should I update versions to pypi ?

If you know how to install from source then you could do

```
papis zotero import --from-bibtex yourbib.bib --outfolder testlibrary
```

Maybe you can try it out, it will work with the master version of papis, that's why I ask you if you
can install yourself ;)

**Comment by alejandrogallo** [comment]
This is now fixed on master
